### ISSUE TITLE
Prometheus metrics accessibility

### ISSUE THREAD

**Issue by madnight** [Traum-Ferienwohnungen/docker-wkhtmltopdf-aas#13]
Is it okay than anyone can access the prometheus metrics or should there be an authentication check?

**Comment by jayme-github** [comment]
I think it's not. Short term might be okay be okay but that should definitely be fixed! Authentication is not an option as that would require us to take special action (configuration) within prometheus.

You should expose the metrics on a different than the production port (that's what we do for other services) to not expose them to the general public.
