### ISSUE TITLE
How to provide external resources?

### ISSUE THREAD

**Issue by mohamnag** [Traum-Ferienwohnungen/docker-wkhtmltopdf-aas#15]
I can not find a way to pass additional resources that an HTML may need to render successfully like external images and fonts. specially fonts are my curreny problem. the command line version of the wkhtmltopdf supports them as it runs locally but what about over this API?

**Comment by madnight** [comment]
Did you tried to pass the font via url? 
example:
`<link href='http://fonts.googleapis.com/css?family=Jolly+Lodger' rel='stylesheet' type='text/css'>
`

**Comment by mohamnag** [comment]
that would work with publicly available fonts but I have some properietary ones. I believe embeded as data URI will work.

**Comment by madnight** [comment]
If you are in a proprietary context you should fork this project and host this service at your company backend, where you have access to local hosted services (company network) to reference a non public URI. The provided API (https://docker-wkhtmltopdf-aas.herokuapp.com) in the Readme.md is only a demo service for testing.
