### ISSUE TITLE
Cannot use parameter without value

### ISSUE THREAD

**Issue by xydro4** [Traum-Ferienwohnungen/docker-wkhtmltopdf-aas#16]
How can we get parameters like _disable-smart-shrinking_ working?

**Comment by madnight** [comment]
Have you tried:
```
  'options': {
        'disable-smart-shrinking':''
    }
```

**Comment by xydro4** [comment]
Yes I have. The response I get is 'invalid arguments'.

**Comment by madnight** [comment]
ok i'll check that

**Comment by madnight** [comment]
okay i created a branch `allow-empty-options` https://github.com/Traum-Ferienwohnungen/docker-wkhtmltopdf-aas/commit/b13cfd8d63e04c35bd6d4dc9b4ba6c8da4165f56 which should address that issue, the tests run successful with `'disable-smart-shrinking':''` https://travis-ci.org/Traum-Ferienwohnungen/docker-wkhtmltopdf-aas Could you checkout that branch and check if that solves the issue? Please keep in mind that i added an extra HTTP basic auth (also described in the readme.md master) to protect all ports and routes of the service.

**Comment by xydro4** [comment]
Just checked. The issue is solved.
