### ISSUE TITLE
temporary files clean-up

### ISSUE THREAD

**Issue by morq** [Traum-Ferienwohnungen/docker-wkhtmltopdf-aas#18]
Is it possible to support some kind of clean-up temporary files (pdf files and directories created in container) or change script to save it in /tmp directory instead of main dir ("/")?

**Comment by madnight** [comment]
Thats a somewhat strange library behaviour that surprised me as well while writing tests. The libs from sindresorhus that i use for temp file creation: https://github.com/sindresorhus/tempfile and https://github.com/sindresorhus/temp-write actually create persistent files in current directory instead of writing a file to /tmp as i initially expected. I'll check if i find a better solution.

**Comment by madnight** [comment]
Okay i just hacked a branch together that should address the issue:
https://github.com/Traum-Ferienwohnungen/docker-wkhtmltopdf-aas/commit/e8c6382ee906d4053f8513b93e36375b1a15d0b5
https://github.com/Traum-Ferienwohnungen/docker-wkhtmltopdf-aas/tree/tmp-file-cleanup

The tmp files will now be written to /tmp and cleaned up after transmission.

**Comment by morq** [comment]
@madnight ill checked it, and it's still not working properly, files are still stored in current directory ("/")

**Comment by madnight** [comment]
@morq have you tried the following steps: 
```bash
npm install
npm run docker
npm run test
```
(install new deps, recompile, run tests)
Here you can see a small screencast how the files get generated in my /tmp dir, followed by cleanup.
http://webmshare.com/yY9Y1

**Comment by morq** [comment]
@madnight i'm not familiar with npm, coffee and so on. I downloaded this code on branch tmp-file-cleanup and i built docker image from Dockerfile. Here u can see a screenshot with file list in docker container after pdf generation. 
https://1drv.ms/i/s!AsxQLx6o7Cmuldk1MIwtWfZ0Uj6HRQ

**Comment by madnight** [comment]
@morq that's interesting, it works locally, but not inside of docker ... okay new commit, i enforce the exact tmp dir location and perform a manual cleanup  https://github.com/Traum-Ferienwohnungen/docker-wkhtmltopdf-aas/commit/900c63558794f9c3e464b45dbeaf5f60940eb575 

should work now, if you pull the changes and rebuild docker

**Comment by madnight** [comment]
merged
