### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by RA1449** [Traum-Ferienwohnungen/docker-wkhtmltopdf-aas#23]
I'm not sure why I keep getting 401 Unauthorized when I send a Post request. I CAN successfully send a Post request to the openlabs/docker-wkhtmltopdf-aas container, however I wanted to analyze the functionality that added to accept Base64 for the Footer in hopes to have the same working for a Cover Page too.

**Comment by madnight** [comment]
Try it like so:

```bash
content=$(echo "<html>Your HTML content</html>" | base64)
footer=$(echo "<html>Your HTML footer</html>" | base64)
curl -vvv -H "Content-Type: application/json" -X POST -d \
    '{"contents": "'"$content"'",
      "options": {
        "margin-top": "20",
        "margin-left": "20",
        "margin-right": "20",
        "margin-bottom": "30"
      },
      "footer": "'"$footer"'"}' \
https://gooduser:secretpassword@docker-wkhtmltopdf-aas.herokuapp.com -o OUTPUT_NAME.pdf
```
As you can see in the last line of the snippet, you have to provide basic auth credentials.
