### ISSUE TITLE
Error in bootprint paginate (create.js:101)

### ISSUE THREAD

**Issue by mverleg** [Traum-Ferienwohnungen/docker-wkhtmltopdf-aas#24]
Thanks for maintaining this fork!

**Steps**

* `git clone https://github.com/traum-ferienwohnungen/docker-wkhtmltopdf-aas`
* `cd docker-wkhtmltopdf-aas`
* `docker build .`

**Error**

    Step 11/17 : RUN bootprint openapi swagger.yaml documentation && npm uninstall -g bootprint bootprint-openapi
     ---> Running in af089576d8b9
    /usr/local/lib/node_modules/bootprint/node_modules/got/dist/source/create.js:101
        got.paginate = async function* (url, options) {
                                     ^
    
    SyntaxError: Unexpected token *
        at createScript (vm.js:80:10)
        at Object.runInThisContext (vm.js:139:10)
        at Module._compile (module.js:616:28)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/usr/local/lib/node_modules/bootprint/node_modules/got/dist/source/index.js:7:18)

P.s. is there any Dockerhub release?

**Comment by mverleg** [comment]
I skipped that step ib the Dockerfile and so far things work. Maybe it's a workaround for others running into this. Might have unintended consequences, I don't know.

**Comment by madnight** [comment]
Alright, yes this step is only required for the self-hosted documentation part, so your build should work just fine. And yes we have releases on docker hub https://hub.docker.com/r/traumfewo/docker-wkhtmltopdf-aas, but they might be a bit dated.

I will provide a fix for that documentation RUN statement.

**Comment by madnight** [comment]
I fixed the build issue by pinning the bootapi version https://github.com/traum-ferienwohnungen/docker-wkhtmltopdf-aas/commit/a5ab1587103d29c260b5659799ed69999f0ad45a
https://travis-ci.org/github/traum-ferienwohnungen/docker-wkhtmltopdf-aas/jobs/699645726
